/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThreatIntelRouteImport } from './routes/threat-intel'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardEmailRouteImport } from './routes/dashboard.$email'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as ApiSendAlertEmailRouteImport } from './routes/api.send-alert-email'
import { Route as ApiIntegrityRouteImport } from './routes/api.integrity'
import { Route as ApiAiAssistantRouteImport } from './routes/api.ai-assistant'

const ThreatIntelRoute = ThreatIntelRouteImport.update({
  id: '/threat-intel',
  path: '/threat-intel',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEmailRoute = DashboardEmailRouteImport.update({
  id: '/dashboard/$email',
  path: '/dashboard/$email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendAlertEmailRoute = ApiSendAlertEmailRouteImport.update({
  id: '/api/send-alert-email',
  path: '/api/send-alert-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrityRoute = ApiIntegrityRouteImport.update({
  id: '/api/integrity',
  path: '/api/integrity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAssistantRoute = ApiAiAssistantRouteImport.update({
  id: '/api/ai-assistant',
  path: '/api/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/business': typeof BusinessRoute
  '/settings': typeof SettingsRoute
  '/threat-intel': typeof ThreatIntelRoute
  '/api/ai-assistant': typeof ApiAiAssistantRoute
  '/api/integrity': typeof ApiIntegrityRoute
  '/api/send-alert-email': typeof ApiSendAlertEmailRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/$email': typeof DashboardEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/business': typeof BusinessRoute
  '/settings': typeof SettingsRoute
  '/threat-intel': typeof ThreatIntelRoute
  '/api/ai-assistant': typeof ApiAiAssistantRoute
  '/api/integrity': typeof ApiIntegrityRoute
  '/api/send-alert-email': typeof ApiSendAlertEmailRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/$email': typeof DashboardEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/business': typeof BusinessRoute
  '/settings': typeof SettingsRoute
  '/threat-intel': typeof ThreatIntelRoute
  '/api/ai-assistant': typeof ApiAiAssistantRoute
  '/api/integrity': typeof ApiIntegrityRoute
  '/api/send-alert-email': typeof ApiSendAlertEmailRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/$email': typeof DashboardEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-docs'
    | '/business'
    | '/settings'
    | '/threat-intel'
    | '/api/ai-assistant'
    | '/api/integrity'
    | '/api/send-alert-email'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/$email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-docs'
    | '/business'
    | '/settings'
    | '/threat-intel'
    | '/api/ai-assistant'
    | '/api/integrity'
    | '/api/send-alert-email'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/$email'
  id:
    | '__root__'
    | '/'
    | '/api-docs'
    | '/business'
    | '/settings'
    | '/threat-intel'
    | '/api/ai-assistant'
    | '/api/integrity'
    | '/api/send-alert-email'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/$email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDocsRoute: typeof ApiDocsRoute
  BusinessRoute: typeof BusinessRoute
  SettingsRoute: typeof SettingsRoute
  ThreatIntelRoute: typeof ThreatIntelRoute
  ApiAiAssistantRoute: typeof ApiAiAssistantRoute
  ApiIntegrityRoute: typeof ApiIntegrityRoute
  ApiSendAlertEmailRoute: typeof ApiSendAlertEmailRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  DashboardEmailRoute: typeof DashboardEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/threat-intel': {
      id: '/threat-intel'
      path: '/threat-intel'
      fullPath: '/threat-intel'
      preLoaderRoute: typeof ThreatIntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$email': {
      id: '/dashboard/$email'
      path: '/dashboard/$email'
      fullPath: '/dashboard/$email'
      preLoaderRoute: typeof DashboardEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-alert-email': {
      id: '/api/send-alert-email'
      path: '/api/send-alert-email'
      fullPath: '/api/send-alert-email'
      preLoaderRoute: typeof ApiSendAlertEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrity': {
      id: '/api/integrity'
      path: '/api/integrity'
      fullPath: '/api/integrity'
      preLoaderRoute: typeof ApiIntegrityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-assistant': {
      id: '/api/ai-assistant'
      path: '/api/ai-assistant'
      fullPath: '/api/ai-assistant'
      preLoaderRoute: typeof ApiAiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDocsRoute: ApiDocsRoute,
  BusinessRoute: BusinessRoute,
  SettingsRoute: SettingsRoute,
  ThreatIntelRoute: ThreatIntelRoute,
  ApiAiAssistantRoute: ApiAiAssistantRoute,
  ApiIntegrityRoute: ApiIntegrityRoute,
  ApiSendAlertEmailRoute: ApiSendAlertEmailRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  DashboardEmailRoute: DashboardEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
